In [2]:
import pandas as pd
import numpy as np

In [5]:
mbta = pd.read_excel(r"C:\\Users\tyler\Documents\mlprjs\mbta.xlsx")
mbta

,MBTA Avg Weekday Unlinked Passenger Trips (thousands),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 50,Unnamed: 51,Unnamed: 52,Unnamed: 53,Unnamed: 54,Unnamed: 55,Unnamed: 56,Unnamed: 57,Unnamed: 58,Unnamed: 59
0,NaN,mode,2007-01,2007-02,2007-03,2007-04,2007-05,2007-06,2007-07,2007-08,...,2011-01,2011-02,2011-03,2011-04,2011-05,2011-06,2011-07,2011-08,2011-09,2011-10
1,1.0,All Modes by Qtr,NaN,NaN,1187.653,NaN,NaN,1245.959,NaN,NaN,...,NaN,NaN,1223.452,NaN,NaN,1302.414,NaN,NaN,1290.549,NaN
2,2.0,Boat,4,3.6,4,4.3,4.9,5.8,6.521,6.572,...,3.14,3.284,3.674,4.251,4.431,5.474,6.581,6.733,5.003,4.484
3,3.0,Bus,335.819,338.675,339.867,352.162,354.367,350.543,357.519,355.479,...,334.958,346.234,380.399,380.446,385.289,376.317,361.585,353.793,388.271,398.456
4,4.0,Commuter Rail,142.2,138.5,137.7,139.5,139,143,142.391,142.364,...,128.396,125.463,134.374,134.169,136.14,135.581,132.41,130.616,136.901,128.72
5,5.0,Heavy Rail,435.294,448.271,458.583,472.201,474.579,477.032,471.735,461.605,...,468.418,504.068,516.73,528.631,528.122,529.528,532.888,508.145,550.137,554.932
6,6.0,Light Rail,227.231,240.262,241.444,255.557,248.262,246.108,243.286,234.907,...,198.45,219.886,227.935,242.28,225.776,221.865,231.01,220.164,244.949,237.768
7,7.0,Pct Chg / Yr,0.02,-0.04,0.114,-0.002,0.049,0.096,-0.037,0.004,...,-0.028,0.008,0.05,0.036,0.05,0.054,0.067,0.052,0.043,0.032
8,8.0,Private Bus,4.772,4.417,4.574,4.542,4.768,4.722,3.936,3.946,...,2.213,2.57,2.559,2.762,2.776,2.815,2.671,2.655,2.843,2.967
9,9.0,RIDE,4.9,5,5.5,5.4,5.4,5.6,5.253,5.308,...,6.735,7.463,8.387,8.145,8.059,8.377,7.902,8.071,8.318,8.598
10,10.0,Trackless Trolley,12.757,12.913,13.057,13.444,13.479,13.323,13.311,13.142,...,11.104,11.695,12.601,12.599,12.291,12.128,11.06,11.091,12.332,12.297
11,11.0,TOTAL,1166.974,1191.639,1204.725,1247.105,1244.755,1246.129,1243.952,1223.323,...,1153.413,1220.663,1286.66,1313.283,1302.884,1292.085,1286.107,1241.268,1348.754,1348.222

In [6]:
mbta_1 = mbta.drop([1,7,11])
mbta_1

,MBTA Avg Weekday Unlinked Passenger Trips (thousands),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 50,Unnamed: 51,Unnamed: 52,Unnamed: 53,Unnamed: 54,Unnamed: 55,Unnamed: 56,Unnamed: 57,Unnamed: 58,Unnamed: 59
0,NaN,mode,2007-01,2007-02,2007-03,2007-04,2007-05,2007-06,2007-07,2007-08,...,2011-01,2011-02,2011-03,2011-04,2011-05,2011-06,2011-07,2011-08,2011-09,2011-10
2,2.0,Boat,4,3.6,4,4.3,4.9,5.8,6.521,6.572,...,3.14,3.284,3.674,4.251,4.431,5.474,6.581,6.733,5.003,4.484
3,3.0,Bus,335.819,338.675,339.867,352.162,354.367,350.543,357.519,355.479,...,334.958,346.234,380.399,380.446,385.289,376.317,361.585,353.793,388.271,398.456
4,4.0,Commuter Rail,142.2,138.5,137.7,139.5,139,143,142.391,142.364,...,128.396,125.463,134.374,134.169,136.14,135.581,132.41,130.616,136.901,128.72
5,5.0,Heavy Rail,435.294,448.271,458.583,472.201,474.579,477.032,471.735,461.605,...,468.418,504.068,516.73,528.631,528.122,529.528,532.888,508.145,550.137,554.932
6,6.0,Light Rail,227.231,240.262,241.444,255.557,248.262,246.108,243.286,234.907,...,198.45,219.886,227.935,242.28,225.776,221.865,231.01,220.164,244.949,237.768
8,8.0,Private Bus,4.772,4.417,4.574,4.542,4.768,4.722,3.936,3.946,...,2.213,2.57,2.559,2.762,2.776,2.815,2.671,2.655,2.843,2.967
9,9.0,RIDE,4.9,5,5.5,5.4,5.4,5.6,5.253,5.308,...,6.735,7.463,8.387,8.145,8.059,8.377,7.902,8.071,8.318,8.598
10,10.0,Trackless Trolley,12.757,12.913,13.057,13.444,13.479,13.323,13.311,13.142,...,11.104,11.695,12.601,12.599,12.291,12.128,11.06,11.091,12.332,12.297

In [7]:
mbta_2 = mbta_1.drop(columns=["MBTA Avg Weekday Unlinked Passenger Trips (thousands)"])
mbta_2

,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,...,Unnamed: 50,Unnamed: 51,Unnamed: 52,Unnamed: 53,Unnamed: 54,Unnamed: 55,Unnamed: 56,Unnamed: 57,Unnamed: 58,Unnamed: 59
0,mode,2007-01,2007-02,2007-03,2007-04,2007-05,2007-06,2007-07,2007-08,2007-09,...,2011-01,2011-02,2011-03,2011-04,2011-05,2011-06,2011-07,2011-08,2011-09,2011-10
2,Boat,4,3.6,4,4.3,4.9,5.8,6.521,6.572,5.469,...,3.14,3.284,3.674,4.251,4.431,5.474,6.581,6.733,5.003,4.484
3,Bus,335.819,338.675,339.867,352.162,354.367,350.543,357.519,355.479,372.598,...,334.958,346.234,380.399,380.446,385.289,376.317,361.585,353.793,388.271,398.456
4,Commuter Rail,142.2,138.5,137.7,139.5,139,143,142.391,142.364,143.051,...,128.396,125.463,134.374,134.169,136.14,135.581,132.41,130.616,136.901,128.72
5,Heavy Rail,435.294,448.271,458.583,472.201,474.579,477.032,471.735,461.605,499.566,...,468.418,504.068,516.73,528.631,528.122,529.528,532.888,508.145,550.137,554.932
6,Light Rail,227.231,240.262,241.444,255.557,248.262,246.108,243.286,234.907,265.748,...,198.45,219.886,227.935,242.28,225.776,221.865,231.01,220.164,244.949,237.768
8,Private Bus,4.772,4.417,4.574,4.542,4.768,4.722,3.936,3.946,4.329,...,2.213,2.57,2.559,2.762,2.776,2.815,2.671,2.655,2.843,2.967
9,RIDE,4.9,5,5.5,5.4,5.4,5.6,5.253,5.308,5.609,...,6.735,7.463,8.387,8.145,8.059,8.377,7.902,8.071,8.318,8.598
10,Trackless Trolley,12.757,12.913,13.057,13.444,13.479,13.323,13.311,13.142,14.393,...,11.104,11.695,12.601,12.599,12.291,12.128,11.06,11.091,12.332,12.297

In [8]:
mbta_3 = mbta_2.melt(id_vars=['Unnamed: 1'], value_vars=mbta_2.columns[0:59],
            value_name="count",var_name = "type")
mbta_3

            Unnamed: 1         type    count
0                 mode   Unnamed: 2  2007-01
1                 Boat   Unnamed: 2        4
2                  Bus   Unnamed: 2  335.819
3        Commuter Rail   Unnamed: 2    142.2
4           Heavy Rail   Unnamed: 2  435.294
..                 ...          ...      ...
517         Heavy Rail  Unnamed: 59  554.932
518         Light Rail  Unnamed: 59  237.768
519        Private Bus  Unnamed: 59    2.967
520               RIDE  Unnamed: 59    8.598
521  Trackless Trolley  Unnamed: 59   12.297

[522 rows x 3 columns]

In [9]:
mbta_4 = mbta_3.pivot(columns = 'Unnamed: 1', 
             values = 'count',
             index=['type']).reset_index().\
rename_axis(None, axis=1) 
mbta_4

,type,Boat,Bus,Commuter Rail,Heavy Rail,Light Rail,Private Bus,RIDE,Trackless Trolley,mode
0,Unnamed: 10,5.469,372.598,143.051,499.566,265.748,4.329,5.609,14.393,2007-09
1,Unnamed: 11,5.145,368.847,146.542,457.741,241.434,4.315,5.806,14.622,2007-10
2,Unnamed: 12,3.763,330.826,145.089,488.348,250.497,4.081,5.667,13.624,2007-11
3,Unnamed: 13,2.985,312.92,141.585,448.268,233.379,3.708,5.062,12.41,2007-12
4,Unnamed: 14,3.175,340.324,142.145,472.624,241.223,4.122,5.535,13.902,2008-01
5,Unnamed: 15,3.111,352.905,142.607,492.1,249.306,4.079,5.704,14.172,2008-02
6,Unnamed: 16,3.512,361.155,137.453,494.046,253.132,4.175,6.164,14.394,2008-03
7,Unnamed: 17,4.164,368.189,140.389,513.204,271.07,4.144,6.263,14.722,2008-04
8,Unnamed: 18,4.015,363.903,142.585,507.952,258.351,4.079,6.279,14.427,2008-05
9,Unnamed: 19,5.189,362.962,142.057,518.349,266.961,4.4,6.294,14.515,2008-06
10,Unnamed: 2,4,335.819,142.2,435.294,227.231,4.772,4.9,12.757,2007-01
11,Unnamed: 20,6.016,370.921,145.731,512.309,270.158,4.548,6.028,14.392,2008-07
12,Unnamed: 21,5.8,361.057,144.565,476.99,239.344,4.286,6.148,13.716,2008-08
13,Unnamed: 22,4.587,389.537,141.907,517.324,258.171,4.878,6.503,15.109,2008-09
14,Unnamed: 23,4.285,357.974,151.957,523.644,250.063,4.556,6.678,13.014,2008-10
15,Unnamed: 24,3.488,345.423,152.952,487.115,232.068,4.302,6.41,12.596,2008-11
16,Unnamed: 25,3.007,325.767,140.81,446.743,205.42,3.42,5.957,11.91,2008-12
17,Unnamed: 26,3.014,338.532,141.448,461.004,215.66,3.584,5.991,12.301,2009-01
18,Unnamed: 27,3.196,360.412,143.529,482.407,228.737,3.604,6.708,9.645,2009-02
19,Unnamed: 28,3.33,353.686,142.893,467.224,222.844,2.586,6.675,11.674,2009-03
20,Unnamed: 29,4.049,359.38,142.34,493.152,238.232,2.824,6.734,11.326,2009-04
21,Unnamed: 3,3.6,338.675,138.5,448.271,240.262,4.417,5,12.913,2007-02
22,Unnamed: 30,4.119,354.75,144.225,475.634,224.962,2.735,6.693,12.49,2009-05
23,Unnamed: 31,4.9,347.865,142.006,473.099,226.259,2.763,6.79,12.382,2009-06
24,Unnamed: 32,6.444,339.477,137.691,470.828,230.308,2.655,6.249,11.426,2009-07
25,Unnamed: 33,5.903,332.661,139.158,466.676,231.783,2.504,6.423,12.05,2009-08
26,Unnamed: 34,4.696,374.26,139.087,500.403,250.922,2.716,6.69,12.79,2009-09
27,Unnamed: 35,4.212,385.868,137.104,513.406,230.739,2.584,6.897,13.252,2009-10
28,Unnamed: 36,3.576,366.98,129.343,480.278,214.711,2.721,6.565,12.651,2009-11
29,Unnamed: 37,3.113,332.394,126.066,440.925,194.446,2.365,6.454,11.62,2009-12
30,Unnamed: 38,3.207,362.226,130.91,464.069,204.396,2.682,6.516,12.265,2010-01
31,Unnamed: 39,3.195,361.138,131.918,480.121,213.136,2.498,6.665,12.558,2010-02
32,Unnamed: 4,4,339.867,137.7,458.583,241.444,4.574,5.5,13.057,2007-03
33,Unnamed: 40,3.481,373.443,131.252,483.397,211.693,2.55,7.066,12.673,2010-03
34,Unnamed: 41,4.452,378.611,131.722,502.374,227.246,2.639,7.166,13.017,2010-04
35,Unnamed: 42,4.415,380.171,128.8,487.4,217.805,2.686,7.1,12.771,2010-05
36,Unnamed: 43,5.411,363.275,129.144,490.263,215.922,2.646,7.46,11.473,2010-06
37,Unnamed: 44,6.513,353.04,122.935,488.587,218.729,2.547,6.965,6.584,2010-07
38,Unnamed: 45,6.269,343.688,129.732,473.731,210.53,2.433,7.045,6.316,2010-08
39,Unnamed: 46,4.699,381.622,132.892,521.099,236.368,2.652,7.349,6.436,2010-09
40,Unnamed: 47,4.402,384.987,131.033,532.403,236.366,2.616,7.646,6.819,2010-10
41,Unnamed: 48,3.731,367.955,130.889,502.887,221.881,2.528,7.444,6.415,2010-11
42,Unnamed: 49,3.156,326.338,121.422,450.433,196.211,2.379,7.199,5.777,2010-12
43,Unnamed: 5,4.3,352.162,139.5,472.201,255.557,4.542,5.4,13.444,2007-04
44,Unnamed: 50,3.14,334.958,128.396,468.418,198.45,2.213,6.735,11.104,2011-01
45,Unnamed: 51,3.284,346.234,125.463,504.068,219.886,2.57,7.463,11.695,2011-02
46,Unnamed: 52,3.674,380.399,134.374,516.73,227.935,2.559,8.387,12.601,2011-03
47,Unnamed: 53,4.251,380.446,134.169,528.631,242.28,2.762,8.145,12.599,2011-04
48,Unnamed: 54,4.431,385.289,136.14,528.122,225.776,2.776,8.059,12.291,2011-05
49,Unnamed: 55,5.474,376.317,135.581,529.528,221.865,2.815,8.377,12.128,2011-06
50,Unnamed: 56,6.581,361.585,132.41,532.888,231.01,2.671,7.902,11.06,2011-07
51,Unnamed: 57,6.733,353.793,130.616,508.145,220.164,2.655,8.071,11.091,2011-08
52,Unnamed: 58,5.003,388.271,136.901,550.137,244.949,2.843,8.318,12.332,2011-09
53,Unnamed: 59,4.484,398.456,128.72,554.932,237.768,2.967,8.598,12.297,2011-10
54,Unnamed: 6,4.9,354.367,139,474.579,248.262,4.768,5.4,13.479,2007-05
55,Unnamed: 7,5.8,350.543,143,477.032,246.108,4.722,5.6,13.323,2007-06
56,Unnamed: 8,6.521,357.519,142.391,471.735,243.286,3.936,5.253,13.311,2007-07
57,Unnamed: 9,6.572,355.479,142.364,461.605,234.907,3.946,5.308,13.142,2007-08

In [10]:
mbta_4.rename(columns = {'mode':'Date'}, inplace = True)

In [11]:
mbta_5 = mbta_4.drop(columns = ["type"])
mbta_5

,Boat,Bus,Commuter Rail,Heavy Rail,Light Rail,Private Bus,RIDE,Trackless Trolley,Date
0,5.469,372.598,143.051,499.566,265.748,4.329,5.609,14.393,2007-09
1,5.145,368.847,146.542,457.741,241.434,4.315,5.806,14.622,2007-10
2,3.763,330.826,145.089,488.348,250.497,4.081,5.667,13.624,2007-11
3,2.985,312.92,141.585,448.268,233.379,3.708,5.062,12.41,2007-12
4,3.175,340.324,142.145,472.624,241.223,4.122,5.535,13.902,2008-01
5,3.111,352.905,142.607,492.1,249.306,4.079,5.704,14.172,2008-02
6,3.512,361.155,137.453,494.046,253.132,4.175,6.164,14.394,2008-03
7,4.164,368.189,140.389,513.204,271.07,4.144,6.263,14.722,2008-04
8,4.015,363.903,142.585,507.952,258.351,4.079,6.279,14.427,2008-05
9,5.189,362.962,142.057,518.349,266.961,4.4,6.294,14.515,2008-06
10,4,335.819,142.2,435.294,227.231,4.772,4.9,12.757,2007-01
11,6.016,370.921,145.731,512.309,270.158,4.548,6.028,14.392,2008-07
12,5.8,361.057,144.565,476.99,239.344,4.286,6.148,13.716,2008-08
13,4.587,389.537,141.907,517.324,258.171,4.878,6.503,15.109,2008-09
14,4.285,357.974,151.957,523.644,250.063,4.556,6.678,13.014,2008-10
15,3.488,345.423,152.952,487.115,232.068,4.302,6.41,12.596,2008-11
16,3.007,325.767,140.81,446.743,205.42,3.42,5.957,11.91,2008-12
17,3.014,338.532,141.448,461.004,215.66,3.584,5.991,12.301,2009-01
18,3.196,360.412,143.529,482.407,228.737,3.604,6.708,9.645,2009-02
19,3.33,353.686,142.893,467.224,222.844,2.586,6.675,11.674,2009-03
20,4.049,359.38,142.34,493.152,238.232,2.824,6.734,11.326,2009-04
21,3.6,338.675,138.5,448.271,240.262,4.417,5,12.913,2007-02
22,4.119,354.75,144.225,475.634,224.962,2.735,6.693,12.49,2009-05
23,4.9,347.865,142.006,473.099,226.259,2.763,6.79,12.382,2009-06
24,6.444,339.477,137.691,470.828,230.308,2.655,6.249,11.426,2009-07
25,5.903,332.661,139.158,466.676,231.783,2.504,6.423,12.05,2009-08
26,4.696,374.26,139.087,500.403,250.922,2.716,6.69,12.79,2009-09
27,4.212,385.868,137.104,513.406,230.739,2.584,6.897,13.252,2009-10
28,3.576,366.98,129.343,480.278,214.711,2.721,6.565,12.651,2009-11
29,3.113,332.394,126.066,440.925,194.446,2.365,6.454,11.62,2009-12
30,3.207,362.226,130.91,464.069,204.396,2.682,6.516,12.265,2010-01
31,3.195,361.138,131.918,480.121,213.136,2.498,6.665,12.558,2010-02
32,4,339.867,137.7,458.583,241.444,4.574,5.5,13.057,2007-03
33,3.481,373.443,131.252,483.397,211.693,2.55,7.066,12.673,2010-03
34,4.452,378.611,131.722,502.374,227.246,2.639,7.166,13.017,2010-04
35,4.415,380.171,128.8,487.4,217.805,2.686,7.1,12.771,2010-05
36,5.411,363.275,129.144,490.263,215.922,2.646,7.46,11.473,2010-06
37,6.513,353.04,122.935,488.587,218.729,2.547,6.965,6.584,2010-07
38,6.269,343.688,129.732,473.731,210.53,2.433,7.045,6.316,2010-08
39,4.699,381.622,132.892,521.099,236.368,2.652,7.349,6.436,2010-09
40,4.402,384.987,131.033,532.403,236.366,2.616,7.646,6.819,2010-10
41,3.731,367.955,130.889,502.887,221.881,2.528,7.444,6.415,2010-11
42,3.156,326.338,121.422,450.433,196.211,2.379,7.199,5.777,2010-12
43,4.3,352.162,139.5,472.201,255.557,4.542,5.4,13.444,2007-04
44,3.14,334.958,128.396,468.418,198.45,2.213,6.735,11.104,2011-01
45,3.284,346.234,125.463,504.068,219.886,2.57,7.463,11.695,2011-02
46,3.674,380.399,134.374,516.73,227.935,2.559,8.387,12.601,2011-03
47,4.251,380.446,134.169,528.631,242.28,2.762,8.145,12.599,2011-04
48,4.431,385.289,136.14,528.122,225.776,2.776,8.059,12.291,2011-05
49,5.474,376.317,135.581,529.528,221.865,2.815,8.377,12.128,2011-06
50,6.581,361.585,132.41,532.888,231.01,2.671,7.902,11.06,2011-07
51,6.733,353.793,130.616,508.145,220.164,2.655,8.071,11.091,2011-08
52,5.003,388.271,136.901,550.137,244.949,2.843,8.318,12.332,2011-09
53,4.484,398.456,128.72,554.932,237.768,2.967,8.598,12.297,2011-10
54,4.9,354.367,139,474.579,248.262,4.768,5.4,13.479,2007-05
55,5.8,350.543,143,477.032,246.108,4.722,5.6,13.323,2007-06
56,6.521,357.519,142.391,471.735,243.286,3.936,5.253,13.311,2007-07
57,6.572,355.479,142.364,461.605,234.907,3.946,5.308,13.142,2007-08

In [41]:
mbta_final = mbta_5.sort_values(by = ["Date"])
mbta_final

,Boat,Bus,Commuter Rail,Heavy Rail,Light Rail,Private Bus,RIDE,Trackless Trolley,Date
10,4,335.819,142.2,435.294,227.231,4.772,4.9,12.757,2007-01
21,3.6,338.675,138.5,448.271,240.262,4.417,5,12.913,2007-02
32,4,339.867,137.7,458.583,241.444,4.574,5.5,13.057,2007-03
43,4.3,352.162,139.5,472.201,255.557,4.542,5.4,13.444,2007-04
54,4.9,354.367,139,474.579,248.262,4.768,5.4,13.479,2007-05
55,5.8,350.543,143,477.032,246.108,4.722,5.6,13.323,2007-06
56,6.521,357.519,142.391,471.735,243.286,3.936,5.253,13.311,2007-07
57,6.572,355.479,142.364,461.605,234.907,3.946,5.308,13.142,2007-08
0,5.469,372.598,143.051,499.566,265.748,4.329,5.609,14.393,2007-09
1,5.145,368.847,146.542,457.741,241.434,4.315,5.806,14.622,2007-10
2,3.763,330.826,145.089,488.348,250.497,4.081,5.667,13.624,2007-11
3,2.985,312.92,141.585,448.268,233.379,3.708,5.062,12.41,2007-12
4,3.175,340.324,142.145,472.624,241.223,4.122,5.535,13.902,2008-01
5,3.111,352.905,142.607,492.1,249.306,4.079,5.704,14.172,2008-02
6,3.512,361.155,137.453,494.046,253.132,4.175,6.164,14.394,2008-03
7,4.164,368.189,140.389,513.204,271.07,4.144,6.263,14.722,2008-04
8,4.015,363.903,142.585,507.952,258.351,4.079,6.279,14.427,2008-05
9,5.189,362.962,142.057,518.349,266.961,4.4,6.294,14.515,2008-06
11,6.016,370.921,145.731,512.309,270.158,4.548,6.028,14.392,2008-07
12,5.8,361.057,144.565,476.99,239.344,4.286,6.148,13.716,2008-08
13,4.587,389.537,141.907,517.324,258.171,4.878,6.503,15.109,2008-09
14,4.285,357.974,151.957,523.644,250.063,4.556,6.678,13.014,2008-10
15,3.488,345.423,152.952,487.115,232.068,4.302,6.41,12.596,2008-11
16,3.007,325.767,140.81,446.743,205.42,3.42,5.957,11.91,2008-12
17,3.014,338.532,141.448,461.004,215.66,3.584,5.991,12.301,2009-01
18,3.196,360.412,143.529,482.407,228.737,3.604,6.708,9.645,2009-02
19,3.33,353.686,142.893,467.224,222.844,2.586,6.675,11.674,2009-03
20,4.049,359.38,142.34,493.152,238.232,2.824,6.734,11.326,2009-04
22,4.119,354.75,144.225,475.634,224.962,2.735,6.693,12.49,2009-05
23,4.9,347.865,142.006,473.099,226.259,2.763,6.79,12.382,2009-06
24,6.444,339.477,137.691,470.828,230.308,2.655,6.249,11.426,2009-07
25,5.903,332.661,139.158,466.676,231.783,2.504,6.423,12.05,2009-08
26,4.696,374.26,139.087,500.403,250.922,2.716,6.69,12.79,2009-09
27,4.212,385.868,137.104,513.406,230.739,2.584,6.897,13.252,2009-10
28,3.576,366.98,129.343,480.278,214.711,2.721,6.565,12.651,2009-11
29,3.113,332.394,126.066,440.925,194.446,2.365,6.454,11.62,2009-12
30,3.207,362.226,130.91,464.069,204.396,2.682,6.516,12.265,2010-01
31,3.195,361.138,131.918,480.121,213.136,2.498,6.665,12.558,2010-02
33,3.481,373.443,131.252,483.397,211.693,2.55,7.066,12.673,2010-03
34,4.452,378.611,131.722,502.374,227.246,2.639,7.166,13.017,2010-04
35,4.415,380.171,128.8,487.4,217.805,2.686,7.1,12.771,2010-05
36,5.411,363.275,129.144,490.263,215.922,2.646,7.46,11.473,2010-06
37,6.513,353.04,122.935,488.587,218.729,2.547,6.965,6.584,2010-07
38,6.269,343.688,129.732,473.731,210.53,2.433,7.045,6.316,2010-08
39,4.699,381.622,132.892,521.099,236.368,2.652,7.349,6.436,2010-09
40,4.402,384.987,131.033,532.403,236.366,2.616,7.646,6.819,2010-10
41,3.731,367.955,130.889,502.887,221.881,2.528,7.444,6.415,2010-11
42,3.156,326.338,121.422,450.433,196.211,2.379,7.199,5.777,2010-12
44,3.14,334.958,128.396,468.418,198.45,2.213,6.735,11.104,2011-01
45,3.284,346.234,125.463,504.068,219.886,2.57,7.463,11.695,2011-02
46,3.674,380.399,134.374,516.73,227.935,2.559,8.387,12.601,2011-03
47,4.251,380.446,134.169,528.631,242.28,2.762,8.145,12.599,2011-04
48,4.431,385.289,136.14,528.122,225.776,2.776,8.059,12.291,2011-05
49,5.474,376.317,135.581,529.528,221.865,2.815,8.377,12.128,2011-06
50,6.581,361.585,132.41,532.888,231.01,2.671,7.902,11.06,2011-07
51,6.733,353.793,130.616,508.145,220.164,2.655,8.071,11.091,2011-08
52,5.003,388.271,136.901,550.137,244.949,2.843,8.318,12.332,2011-09
53,4.484,398.456,128.72,554.932,237.768,2.967,8.598,12.297,2011-10